### ISSUE TITLE
Construccion de la ventana1 primera parte 

### ISSUE THREAD

**Issue by JuanesUpegui** [JuanesUpegui/Clase-9#1]
Construir la ventana1 y hacer el formulario para ingresar la informacion del cliente

**Comment by SantiagoAbello1** [comment]
saludos, voy a encargarme de esta funcionalidad

**Comment by JuanesUpegui** [comment]
Listo trabajo cumplido, por favor favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro de usuario
